name: Integ Actions
on: [workflow_dispatch, pull_request]
jobs:
  Integration-Tests:
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Enforce docker-compose v1
        run: |
          echo "GitHub starts to switch runners to include docker-compose v2"
          echo "which uses 'docker compose' command to replace 'docker-compose'"
          echo "this would cause issues in our test validation so we enforce v1 here"
          echo "https://github.com/actions/runner-images/commit/2a4bc14da46f1f8e358aa902a69edb9bef135472"
          sudo apt-get remove -y docker-compose-plugin
          sudo pip install docker-compose==1.29.2
          docker --version
          docker-compose --version
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Clone pyenv
        run: git clone https://github.com/pyenv/pyenv.git ~/.pyenv
      - name: Clone pyenv-virtualenv
        run: git clone https://github.com/pyenv/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv
      - name: Install JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'
      - run: echo "JAVA8_HOME=$JAVA_HOME" >> $GITHUB_ENV
      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - run: echo "JAVA11_HOME=$JAVA_HOME" >> $GITHUB_ENV
      - name: Install JDK 15
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '15'
      - run: echo "JAVA15_HOME=$JAVA_HOME" >> $GITHUB_ENV
      - name: Install JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '16'
      - run: echo "JAVA16_HOME=$JAVA_HOME" >> $GITHUB_ENV
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - run: echo "JAVA17_HOME=$JAVA_HOME" >> $GITHUB_ENV
      - name: Run the CI build_it script
        run: bash .ci/build.sh build_it ${{ matrix.python-version }}
        env:
          BENCHMARK_HOME: env.GITHUB_WORKSPACE
