name: Integ Actions
on: [workflow_dispatch, pull_request]
jobs:
  Integration-Tests:
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Clone pyenv
        run: git clone https://github.com/pyenv/pyenv.git ~/.pyenv
      - name: Clone pyenv-virtualenv
        run: git clone https://github.com/pyenv/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv
      - name: Install JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install JDK 15
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'
      - name: Install JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Run the CI build_it script
        run: bash .ci/build.sh build_it ${{ matrix.python-version }}
        env:
          BENCHMARK_HOME: env.GITHUB_WORKSPACE